version: '3.5'

services:
  db_auth:
    container_name: db_auth
    image: postgres:14.15-alpine
    restart: always
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin

